spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: portfolio.cy4ymq3m97fp.ap-northeast-2.rds.amazonaws.com/lunchselect
    username: admin
    password: 1q2w3e4r
    
mybatis:
  mapper-locations:
    - /mappers/*.xml 
    
jwt:
  secret: qJzUmGueQXDTxcXJyWUZa2oVwieBrVF41ozvRaHcW4uJ8Y4sJqHQC8WbvNoTC63k

